export const icons = {
  car: { ios: 'car.fill', android: 'directions_car' },
  carSide: { ios: 'car.side', android: 'directions_car' },
  gauge: { ios: 'gauge.with.dots.needle.67percent', android: 'speed' },
  chart: { ios: 'chart.bar.xaxis', android: 'bar_chart' },
  settings: { ios: 'gearshape', android: 'settings' },
  antenna: { ios: 'antenna.radiowaves.left.and.right', android: 'bluetooth' },
  stop: { ios: 'stop.fill', android: 'stop' },
  play: { ios: 'play.fill', android: 'play_arrow' },
  warning: { ios: 'exclamationmark.triangle.fill', android: 'warning' },
  checkCircle: { ios: 'checkmark.circle.fill', android: 'check_circle' },
  check: { ios: 'checkmark', android: 'check' },
  chevronRight: { ios: 'chevron.right', android: 'chevron_right' },
  chevronDown: { ios: 'chevron.down', android: 'keyboard_arrow_down' },
  close: { ios: 'xmark', android: 'close' },
  plus: { ios: 'plus', android: 'add' },
  trash: { ios: 'trash', android: 'delete' },
  share: { ios: 'square.and.arrow.up', android: 'share' },
  info: { ios: 'info.circle', android: 'info' },
  doc: { ios: 'doc.text', android: 'description' },
  table: { ios: 'tablecells', android: 'table_chart' },
  archive: { ios: 'archivebox', android: 'inventory_2' },
  restore: { ios: 'arrow.down.doc', android: 'restore_page' },
  code: { ios: 'chevron.left.forwardslash.chevron.right', android: 'code' },
  refresh: { ios: 'arrow.clockwise', android: 'refresh' },
  location: { ios: 'location.fill', android: 'my_location' },
  pin: { ios: 'mappin.circle.fill', android: 'location_on' },
  flag: { ios: 'flag.checkered', android: 'sports_score' },
  shield: { ios: 'checkmark.shield', android: 'verified_user' },
  lock: { ios: 'lock.fill', android: 'lock' },
  clock: { ios: 'clock', android: 'schedule' },
  history: { ios: 'clock.arrow.circlepath', android: 'history' },
  calendar: { ios: 'calendar', android: 'calendar_month' },
  briefcase: { ios: 'briefcase.fill', android: 'work' },
  house: { ios: 'house.fill', android: 'home' },
  building: { ios: 'building.2.fill', android: 'apartment' },
  person: { ios: 'person.crop.circle', android: 'account_circle' },
  pencil: { ios: 'pencil', android: 'edit' },
  note: { ios: 'text.bubble', android: 'chat_bubble' },
  bell: { ios: 'bell.badge', android: 'notifications' },
  euro: { ios: 'eurosign.circle', android: 'euro' },
  scale: { ios: 'building.columns', android: 'account_balance' },
  globe: { ios: 'globe', android: 'language' },
  heart: { ios: 'heart', android: 'favorite' },
  road: { ios: 'road.lanes', android: 'road' },
  route: { ios: 'point.topleft.down.to.point.bottomright.curvepath', android: 'route' },
  ruler: { ios: 'ruler', android: 'straighten' },
  minimize: { ios: 'chevron.down', android: 'expand_more' },
  more: { ios: 'ellipsis', android: 'more_horiz' },
  question: { ios: 'questionmark.circle', android: 'help' },
  voidIcon: { ios: 'xmark.circle', android: 'cancel' },
  gps: { ios: 'location.north.line.fill', android: 'navigation' },
  hand: { ios: 'hand.draw', android: 'draw' },
  fuel: { ios: 'fuelpump', android: 'local_gas_station' },
  wrench: { ios: 'wrench.and.screwdriver', android: 'build' },
  maps: { ios: 'map', android: 'map' },
} as const;

export type IconName = keyof typeof icons;

export const filledOnAndroid: Partial<Record<IconName, boolean>> = {
  car: true,
  play: true,
  stop: true,
  warning: true,
  checkCircle: true,
  location: true,
  lock: true,
  pin: true,
  briefcase: true,
  house: true,
  building: true,
  gps: true,
};
